config/routes.rb
Rails.application.routes.draw do
  resources :websites
  post 'websites/:id/deploy', to: 'websites#deploy', as: "deploy_website"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/website.rb
class Website < ApplicationRecord
  validates :firebase_project_id, uniqueness: true

  extend FriendlyId
  friendly_id :firebase_project_id, use: :slugged
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ActionController::HttpAuthentication::Token::ControllerMethods

  protected

  def restrict_access
    website = Website.friendly.find(params[:id])
    authenticate_or_request_with_http_token do |token, options|
      firebase = FirebaseService.new(JSON.parse(website.firebase_config))
      validated_user = firebase.validate_token(token)
      @current_user = validated_user
      firebase.user_is_editor? validated_user
    end
  end
end

app/controllers/websites_controller.rb
class WebsitesController < ApplicationController
  before_action :restrict_access, only: :deploy
  skip_before_action :verify_authenticity_token, only: [:deploy]

  http_basic_authenticate_with name: ENV["app_name"], password: ENV["app_password"], except: :deploy

  def index
    @websites = Website.order(:created_at)
  end

  def show
    @website = Website.friendly.find(params[:id])
    render json: @website
  end

  def new
    @website = Website.new
    @submit_action = "create"
  end

  def create
    @website = Website.new(website_params)
    if @website.save
      render json: @website, status: :created
    end
  end

  def edit
    @website = Website.friendly.find(params[:id])
    @submit_action = "update"
    render :new
  end

  def update
    @website = Website.friendly.find params[:id]
    @website.update(website_params)

    render json: @website, status: :ok
  end

  def destroy
    @website = Website.friendly.find params[:id]
    @website.destroy
    redirect_to websites_url
  end

  def deploy
    @website = Website.friendly.find params[:id]
    PublishWebsiteJob.perform_later(@website, @current_user)
    begin
      render json: { message: "The website is being published. You will be notified by email when your changes are live.", status: :ok }
    rescue DeploymentError => e
      render json: { error: e, status: :unprocessable_entity }
    end
  end

  def website_params
    params
      .require(:website)
      .permit(
        :project_name,
        :source_repo,
        :firebase_project_id,
        :cloudflare_zone_id,
        :gatsby_env,
        :firebase_env,
        :firebase_config,
        :firebase_config_staging,
        :custom_deploy_command,
        :environment_variables)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/websites_helper.rb
module WebsitesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Less CMS</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/websites/index.html.erb
<div class="page">
  <div class="container">

    <header>
      <h1>All projects</h1>
    </header>
    <main>
      <table class="projects-table">
        <tbody>
          <% @websites.each do |website| %>
            <tr class="project">
              <td><%= website.project_name %></td>
              <td><%= website.firebase_project_id %></td>
              <td><%= link_to "Edit project", edit_website_path(website) %></td>
              <td><%= link_to "Delete project", website_path(website), method: :delete, data: { confirm: 'Are you sure you want to delete this project?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <div>
        <%= link_to "New project", new_website_path, class: "btn btn-new" %>
      </div>
    </main>

  </div>
</div>

app/views/websites/new.html.erb
<div class="page">
  <div class="container">

    <header>
      <h1>Create a new project</h1>
    </header>
    <main>
      <div class="form-container">
        <%= form_for @website, url: { action: @submit_action }, html: { class: "form" } do |f| %>
          <div>
            <%= label_tag(:project_name, "Project name") %>
            <%= f.text_field :project_name %>
          </div>

          <div>
            <%= label_tag(:source_repo, "Source repo") %>
            <%= f.text_field :source_repo %>
          </div>

          <div>
            <%= label_tag(:firebase_project_id, "Firebase project ID") %>
            <%= f.text_field :firebase_project_id %>
          </div>

          <div>
            <%= label_tag(:cloudflare_zone_id, "Cloudflare zone ID") %>
            <%= f.text_field :cloudflare_zone_id %>
          </div>

          <div>
            <%= label_tag(:firebase_config, "[DEFAULT] Firebase config JSON") %>
            <%= f.text_area :firebase_config, rows: 10, placeholder: '{
  "apiKey": "",
  "authDomain": "",
  "databaseURL": "",
  "projectId": "",
  "storageBucket": "",
  "messagingSenderId": "",
  "serviceAccountKey": {}
}'
            %>
          </div>

          <div>
            <%= label_tag(:firebase_config_staging, "[STAGING] Firebase config JSON") %>
            <%= f.text_area :firebase_config_staging, rows: 10, placeholder: '{
  "apiKey": "",
  "authDomain": "",
  "databaseURL": "",
  "projectId": "",
  "storageBucket": "",
  "messagingSenderId": "",
  "serviceAccountKey": {}
}'
            %>
          </div>

          <div>
            <%= label_tag(:gatsby_env, "Gatsby environment") %>
            <%= f.text_field :gatsby_env, placeholder: "staging" %>
          </div>

          <div>
            <%= label_tag(:firebase_env, "Firebase environment") %>
            <%= f.text_field :firebase_env, placeholder: "staging" %>
          </div>

          <div>
            <%= label_tag(:environment_variables, "Environment variables") %>
            <%= f.text_area :environment_variables, rows: 10, placeholder: 'API_KEY=' %>
          </div>

          <div>
            <%= label_tag(:custom_deploy_command, "Custom deploy command" ) %>
            <%= f.text_field :custom_deploy_command %>
          </div>

          <div><%= f.submit "Save", class: "btn" %></div>

        <% end %>
      </div>
    </main>

  </div>
</div>